[Morning Brunch]: singinu
wecode-bootcamp-korea/26-1st-Morning-Brunch-backend pull request #3
Opened 2021-11-03 10:20 UTC by qudans1237

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 view 작성, 로그인 정보(email, password)
2. 로그인 할 때 email, 비밀번호 필수 항목 설정
3. 계정이나 패스워드 Key가 전달되지 않았을 경우 KEY_ERROR, status 400 반환
4. 계정을 잘못 입력한 경우 INVALID_USER, status 401반환
5. 로그인 성공시 SUCCESS, status 200반환
6. 로그인 JWT 적용
7. 사용자의 정보가 존재/일치 할 경우 사용자 정보중 민감하지 않은 정보를 담은 토큰을 생성
8. 로그인 성공 시 토큰을 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 아직 JWT에 대한 이해도가 만족스럽지 않아 좀더 스스로 공부를 할 것입니다.

<br />

## :: 기타 질문 및 특이 사항
-(email-data['email'] 코드 중복을 좀더 간결하게 표현하여 개선할 수 있는 방향이 있을거 같은데 어렵습니다

2021-11-04 02:42 UTC, lordmyshepherd requested changes

2021-11-04 02:42 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({"error_message" : "KEY_ERROR"}, status=400)
SignInView만 올려주세요!
SignUpView는 이전 PR에 이미 올리셨습니다! 하나의 기능만 올릴 수 있도록 해주세요!

2021-11-04 02:42 UTC, lordmyshepherd commented on users/views.py
> +
마지막 빈 줄은 지워주세요~

2021-11-04 02:42 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message':'USER_DOES_NOT_EXIST'}, status=404)
1. `user = User.objects.get(email=data['email'])`
2. `if not User.objects.filter(email=data['email']).exists():` 

1번 코드 2번 코드 둘 다 필요할까요?

2021-11-05 01:30 UTC, lordmyshepherd requested changes

2021-11-05 01:30 UTC, lordmyshepherd commented on users/views.py
> +class SignUpView(View):
여전히 SignUpView 코드도 올라왔네요. 이미 merge된 코드입니다. 지워주세요!

2021-11-05 05:55 UTC, qudans1237 commented on users/views.py
> +            return JsonResponse({"error_message" : "KEY_ERROR"}, status=400)
넵! 확인했습니다

2021-11-05 05:55 UTC, qudans1237 commented on users/views.py
> +
넵 확인했습니다!

2021-11-05 05:58 UTC, qudans1237 commented on users/views.py
> +                return JsonResponse({'message':'USER_DOES_NOT_EXIST'}, status=404)
User.objects.get(email=data['email']) 
이라는 내용에서 get과 filter에 기능이 위 와 같은 상황에선 동일한 작용을 한다고 생각하여 
if not user.exists(): 로 가독성을 좀더 높여보았습니다 :)

2021-11-07 13:34 UTC, gshduet commented
병민님 일요일 저녁에 알람 울리게 해드린 점 사과드립니다. 
현재 이 pr에 올라오면 안될 csv파일들과 db_uploader.py 이 같이 commit 되어 push 되었습니다. 죄송합니다..
git add 하는 과정에서 git add . 명령어로 한 번에 올릴게 아니라 각각의 파일들을 올렸어야 했는데 그동안 저 명령어만 써왔던 바람에 익숙한 방식대로 처리했던 저희의 불찰입니다. 앞으로 수정되는 파일들만 add해 푸쉬하도록 하겠습니다. 다시 한 번 죄송하다는 말씀 드립니다.

언급해주신 피드백들 반영하고 csv파일들과 db_uploader.py 파일은 .gitignore에 추가해 최신화 한 뒤 새로운 pr 올릴까 하는데 괜찮은 방법인지 여쭙습니다..!

2021-11-07 13:45 UTC, lordmyshepherd commented
> 병민님 일요일 저녁에 알람 울리게 해드린 점 사과드립니다. 현재 이 pr에 올라오면 안될 csv파일들과 db_uploader.py 이 같이 commit 되어 push 되었습니다. 죄송합니다.. git add 하는 과정에서 git add . 명령어로 한 번에 올릴게 아니라 각각의 파일들을 올렸어야 했는데 그동안 저 명령어만 써왔던 바람에 익숙한 방식대로 처리했던 저희의 불찰입니다. 앞으로 수정되는 파일들만 add해 푸쉬하도록 하겠습니다. 다시 한 번 죄송하다는 말씀 드립니다.
> 
> 언급해주신 피드백들 반영하고 csv파일들과 db_uploader.py 파일은 .gitignore에 추가해 최신화 한 뒤 새로운 pr 올릴까 하는데 괜찮은 방법인지 여쭙습니다..!

push 하시고 최종적으로 다시 한번 확인해주셔서 감사합니다!
말씀해주신 방향대로 작업 해주시면 👍 👍 

주말에도 고생 많으십니다!! 뽜이링!! 🔥 🔥

2021-11-08 00:56 UTC, closed without merging